### PR TITLE
[PAN-1730] contracts ABI versioning

### PR DESCRIPTION
**Pull request by danut13**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Introduce versioning for the smart contracts ABI.

This is a breaking change!

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
The current version of the smart contracts is 1.1.1 https://github.com/pantos-io/ethereum-contracts/releases/tag/1.1.1
Should the `contracts/v1.0.0` be changed by `contracts/v1.1.1`?

**Comment by danut13** [comment]
@juanmanuel-tirado The currently used contracts are the one from the 1.0.0 version. We are not on the latest version.

**Comment by jacekv** [comment]
Why do we need the versioning? I assume that you guys talked about all that before I started, so that's why I am asking :)
What problem(s) is this going to solve?

**Review by markuslevonyak — DISMISSED** [review]

**Comment by danut13** [comment]
@jacekv upstream projects (service node, validator node) can intend to use older versions of the smart contracts and not change right away to the latest released version, so we want to decouple the process of introducing new smart contracts ABIs from the adaptation of the code in the upstream project. Also, it's a good practice to explicitly specify which version of the contracts you are using to avoid confusion

**Comment by jacekv** [comment]
@danut13 Thanks :)

**Comment by juanmanuel-tirado** [comment]
This requires a rebase with main to update poetry.

**Review by markuslevonyak — APPROVED** [review]

**Review by juanmanuel-tirado — APPROVED** [review]

**Pull request merged**
